addSbtPlugin("org.jetbrains.scala"       % "sbt-ide-settings" % "1.1.1")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"     % "0.1.20")
addSbtPlugin("io.spray"                  % "sbt-revolver"     % "0.9.1")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"     % "2.4.6")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"    % "2.0.0-M4")
